### ISSUE TITLE
Introduce static analysis :)

### ISSUE THREAD

**Issue by szepeviktor** [tim-field/graphql-wp#46]
```bash
composer require --dev "szepeviktor/phpstan-wordpress:^0.6.2" php-stubs/woocommerce-stubs
vendor/bin/phpstan analyze -l 4
```

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src/
    scanFiles:
        - vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
```
